/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.dao.UsuarioDAO;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author HI andres
 */
public class VentanaInicio extends javax.swing.JFrame {
private VentanaIniciarSesion ventanaIniciarSesion;
private VentanaResgistrar ventanaResgistrar;
private ControladorUsuario controladorUsuario;
private UsuarioDAO usuarioDAO;
private VentanaPrincipal ventanaPrincipal;
private Locale localizacion;
private ResourceBundle mensaje;
    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        usuarioDAO=new UsuarioDAO();
        ventanaPrincipal=new VentanaPrincipal();
        controladorUsuario=new ControladorUsuario(usuarioDAO);
        ventanaResgistrar= new VentanaResgistrar(controladorUsuario);
        ventanaIniciarSesion=new VentanaIniciarSesion(controladorUsuario,ventanaPrincipal);
        //agregar ventanas internas
        jDesktopPane1.add(ventanaIniciarSesion);
        jDesktopPane1.add(ventanaResgistrar);
        
       //internacionalidad
       localizacion = new Locale("es", "EC");
       mensaje = ResourceBundle.getBundle("ec.edu.ups.idioma.mensajes", localizacion);   
    }
public void cambiarIdioma(String idioma,String localidad){
localizacion = new Locale(idioma, localidad);
        mensaje = ResourceBundle.getBundle("ec.edu.ups.idioma.mensajes", localizacion);
        btnIniciarSesion.setText(mensaje.getString("IniciarSesion"));
        btnRegistrar.setText(mensaje.getString("RegistrarUsuario"));
        jMenuInicio.setText(mensaje.getString("Inicio"));
        jMenuIdioma.setText(mensaje.getString("Idioma"));
        menuEspañol.setText(mensaje.getString("Español"));
        menuIngles.setText(mensaje.getString("Ingles"));
        salir.setText(mensaje.getString("Salir"));
        labelTitulo.setText(mensaje.getString("Titulo"));
        if(ventanaIniciarSesion!=null){
        ventanaIniciarSesion.setMensaje(mensaje);
        ventanaIniciarSesion.cambiarIdioma(idioma, localidad);
        ventanaResgistrar.setMensaje(mensaje);
        ventanaResgistrar.cambiarIdioma(idioma, localidad);
        ventanaPrincipal.setMensaje(mensaje);
        ventanaPrincipal.cambiarIdioma(idioma, localidad);
        }
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();
        jMenuIdioma = new javax.swing.JMenu();
        menuEspañol = new javax.swing.JMenuItem();
        menuIngles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Distribuidora DTP");

        jPanel1.setBackground(new java.awt.Color(0, 143, 227));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 200));

        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar Usuario");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        labelTitulo.setText("Distribuidora DTP");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/transporte.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnIniciarSesion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnRegistrar)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion)
                        .addGap(65, 65, 65)
                        .addComponent(btnRegistrar)
                        .addGap(125, 125, 125))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        jMenuInicio.setText("Inicio");

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/salida.png"))); // NOI18N
        salir.setText("Salir");
        jMenuInicio.add(salir);

        jMenu.add(jMenuInicio);

        jMenuIdioma.setText("Idioma");

        menuEspañol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/ecuador.png"))); // NOI18N
        menuEspañol.setText("Español");
        menuEspañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEspañolActionPerformed(evt);
            }
        });
        jMenuIdioma.add(menuEspañol);

        menuIngles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/estados-unidos.png"))); // NOI18N
        menuIngles.setText("Ingles");
        menuIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInglesActionPerformed(evt);
            }
        });
        jMenuIdioma.add(menuIngles);

        jMenu.add(jMenuIdioma);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
       ventanaIniciarSesion.setVisible(true);

    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       ventanaResgistrar.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void menuEspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEspañolActionPerformed
       localizacion=new Locale("es","EC");
       this.cambiarIdioma("es", "EC");
    }//GEN-LAST:event_menuEspañolActionPerformed

    private void menuInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInglesActionPerformed
       localizacion=new Locale("en","UK");
       this.cambiarIdioma("en", "UK"); // TODO add your handling code here:
    }//GEN-LAST:event_menuInglesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenuIdioma;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JMenuItem menuEspañol;
    private javax.swing.JMenuItem menuIngles;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
